config/routes.rb
ProjectGorilla::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "users/new"

  get "users/create"

  get "users/update"

  get "users/edit"
  
  get "users/index"

  get "users/delete"

  get "pages/index"

  get "pages/kontakt"

  get "pages/om"

  root                 :to => "pages#index"
  match '/kontakt',    :to => "pages#kontakt"
  match "/om_oss",     :to => "pages#om"
  match "/registrering", :to => "users#new"
  match '/loggain',  :to => 'sessions#new'
  match '/loggaut', :to => 'sessions#destroy'
  match '/users',   :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
      return nil if user.nil?
      return user if user.has_password?(submitted_password)
    end
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
  private 
  
  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end



# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  encrypted_password :string(255)
#  salt               :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  admin              :boolean
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
  before_filter :check_cookies
  include SessionsHelper
def set_locale
  I18n.locale = params[:sv] || I18n.default_locale
end
def check_cookies
  if !cookies[:remember_token].nil? && !signed_in?
    #user = User.authenticate_with_salt(*remember_token)
    #sign_in_with_cookies user
  end
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @title = "Start"
  end

  def kontakt
    @title = "Kontakt"
  end

  def om
    @title = "Om oss"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @title = "Logga in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Felaktiga uppgfiter. Testa igen!"
      @title = "Logga in"
      render 'new'
    else
      if params[:remember_me]
        create_cookies user
      end
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :index, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => [:destroy, :index]
  before_filter :signedin_user,:only => [:new, :create]    
  def new
    @user = User.new
    @title = "Registrering"
  end  

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Registreringen lyckades!"
      redirect_to @user
    else
      @title = "Registrering"
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Uppgifter uppdaterade"
      redirect_to @user
    else
      @title = "Uppdatera uppgifter"
      render 'edit'
    end
  end

  def edit
    @title = "Uppdatera uppgifter"
  end

  def destroy
    user = User.find(params[:id])
    if !user.admin?
      user.destroy
      flash[:success] = "User destroyed."
    else
      flash[:error] = "You can't remove another admin"
    end
    redirect_to users_path
  end
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  private

    def authenticate
      deny_access unless signed_in?
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
    def signedin_user
      redirect_to(root_path) unless !signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #return a title
  def title
    base_title = "The Gorilla Project"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  def logo
    image_tag("logo_gorilla.png", :alt => "Project Gorilla")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  def sign_in_with_cookies(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  def current_user?(user)
    user == current_user
  end
  def signed_in?
    !current_user.nil?
  end
  def sign_out
    session.delete(:remember_token)
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def authenticate
    deny_access unless signed_in?
  end
  def deny_access
    store_location
    redirect_to loggain_path, :notice => "Logga in om du vill se denna sidan."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  def create_cookies(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
  end
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || session[:remember_token] || [nil, nil]
    end
    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_css.html.erb
<%= stylesheet_link_tag 'reset', :media => 'screen' %>
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'style', :media => 'screen' %>

app/views/layouts/_footer.html.erb
<footer>
 
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>    
</header>
<% if !signed_in? %>
<nav id="main-nav-out">
  
  <%= form_for(:session, :url => sessions_path) do |f| %>
<section id="loginform">
  <span class="loginfield">
    <%= f.label :email %>
    <%= f.text_field :email%>
  </span>
  <span class="loginfield">
    <%= f.label :password, "Lösenord" %>
    <%= f.password_field :password %>
  </span>
  <span class="loginfield">
    <%= f.label :remember_me, "Kom ihåg?" %>
    <input type="checkbox" name="remember_me" id="remember_me" checked> 
  </span>
  <span class="loginactions">
    <%= f.submit "Logga in" %>
  </span>
  
</section>
<% end %>

<ul>
    <li class="round"><%= link_to "Start", root_path %></li>
    <li class="round"><%= link_to "Om oss", om_oss_path %></li>
    <li class="round"><%= link_to "Kontakt", kontakt_path %></li>
  </ul>
</nav>

<% else %>
<nav id="main-nav-in">
<ul>
    <li class="round"><%= link_to "Start", root_path %></li>
    <li class="round"><%= link_to "Profil", current_user %></li>
    <li class="round"><%= link_to "Användarinställningar", edit_user_path(current_user) %></li>
    <% if current_user.admin? %>
    <li class="round"><%= link_to "Användare", users_path %></li>
    <% end %>
    <li class="round"><%= link_to "Om oss", om_oss_path %></li>
    <li class="round"><%= link_to "Kontakt", kontakt_path %></li>
    <li class="round"><%= link_to "Logga ut", loggaut_path, :method => :delete %></li>
  </ul>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/css' %>
  <%#= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  <section id="container">
    <%= render 'layouts/header'%>
    <section id="content">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>">
         <p><%= value%></p>
        </div>
      <% end %>
      <%= yield %>
    </section>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>
  </container>
</body>
</html>

app/views/pages/index.html.erb
<h1>Välkommen!</h1>
<p>Detta är startsidan. Så grymt bra!</p>

app/views/pages/kontakt.html.erb
<h1>Pages#kontakt</h1>
<p>Find me in app/views/pages/kontakt.html.erb</p>

app/views/pages/om.html.erb
<h1>Pages#om</h1>
<p>Find me in app/views/pages/om.html.erb</p>

app/views/pages/registrera.html.erb
<h1>Pages#registrera</h1>
<p>Find me in app/views/pages/registrera.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= object.errors.count %> 
        fel förhindrade denna <%= object.class.to_s.underscore.humanize.downcase %> 
        från att registreras:</h2>
    <p>Det var problem med följande fält:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
  <p class="field">
    <%= f.label :name, "Namn" %><br />
    <%= f.text_field :name%>
  </p>
  <p class="field">
    <%= f.label :email, "Email" %><br />
    <%= f.text_field :email %>
  </p>
  <p class="field">
    <%= f.label :password, "Lösenord" %><br />
    <%= f.password_field :password %>
  </p>
  <p class="field">
    <%= f.label :password_confirmation, "Bekräfta lösenord" %><br />
    <%= f.password_field :password_confirmation %>
  </p>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
</li>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Uppdatera uppgifter</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= render 'fields', :f => f %>
  <div class="editform">
  <p class="actions">
    <%= f.submit "Update" %><br />
  </p>
  
<% end %>
</div>
<div>
  <%= gravatar_for @user %>
  <a href='http://gravatar.com/emails' target=_blank>Change</a>

app/views/users/index.html.erb
<h1>Användarlista</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Registrera dig!</h1>
  
<%= form_for(@user) do |f| %>

  <%= render 'fields', :f => f %>
  <div class="signupform">
  <p class="actions">
    <%= f.submit "Logga in" %><br /> 
  </p>
</div>
<% end %>

app/views/users/show.html.erb
<section class='profileinfo'>
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  <aside id="profilesidebar" class='round'>
    <p class='bold'>Namn: <%= @user.name%></p>
    <p class='bold'>URL: <%= link_to user_path(@user), @user%></p>
  </aside>
</section>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>